### ISSUE TITLE
[hchang] CPP00 - ex01 (cin vs getline / static member var)

### ISSUE THREAD

**Issue by change-challenge** [42-CPP-GIT/CPP_GIT#10]
# ex01 

## cin vs getline

cin : 표준 입력 버퍼에서 공백이나 탭, 개행 입력 시 공백 이전까지의 값만 결과로 받아들인다. `(BUT 받은 문자는 버퍼에 남아있습니다. 이것이 문제를 만들어냅니다. )`
getline : 문자열 입력 후 개행('\n')이 있을 때까지 다 보고, `버퍼를 비운다. `
```
int n;
string str;

cin >> n;
// cin.ignore(); // 입력 버퍼의 모든 내용을 제거해줌. 없으면 '\n'이 str에 들어감
getline(cin, str);
```
상단에 코드에서 cin.ignore이 없으면 '3'하고 엔터를 누르면 프로그램 종료가 됩니다.
이유는 즉슨, 
cin은 개행이나 공백 이전까지의 값을 가져오기 때문에 '3\n'에서 3만 `int n`으로 들어가고 버퍼를 비우지 않습니다.
즉, 버퍼에 '\n'이 남아있습니다.
getline함수는 개행을 포함하여 가져오는데 버퍼에 '\n'이 있기에 '\n'를 가져오고 버퍼를 비웁니다. 

즉, str에는 개행이 들어가게 됩니다. 
하여, n과 str에 값을 넣으려면 버퍼를 지워주는  cin.ignore()을 적어줍니다. 

그렇기 때문에 CPP00 - ex01에서 cin으로 ADD를 하게 되면 마지막 `Darkest Secret`에서 
`i think ~` 이런식으로 적게 되면 `i (스페이스바) think`이기에 `Darkest Secret`에 `i`만 들어가게 됩니다. 

## static member var
- **static 멤버 변수** : 모든 객체가 한 메모리를 공유하는 멤버 변수. 객체 별로 각각 할당되는 멤버가 아니라 모든 객체가 공유하는 멤버다. ( Data 세그먼트에 존재)
- 객체 생성 전에도 메모리 존재
    -> 따라서 `객체 생성 전에 반드시 미리 초기화`를 해주어야 한다. (전역범위에서 // h가 아닌 cpp파일에서)

그런데 static 멤버 변수가 private이라면 ?
=> `static멤버는 클래스 내부에선 초기화가 불가능하므로 private하더라도 클래스 외부에서 정의가 가능하다!!!! `

**Comment by jeongmino** [comment]
hchang님이 기록하신 cin, getline에 대한 정리 잘 봤습니다. 덕분에 앞으로 두 함수를 잘 구분해서 쓸 것 같아요.
static var에 대한 정의도 잘 이해가 되지만 아직 어떤 상황에서 static, private static member를 쓸 지 모르겠어요.
혹시 이에 대한 간략한 예시가 있을까요?
