### ISSUE TITLE
[jinypark/CPP00] - ex00(string , endl), ex01(EOF, CTRL+D), ex02(생성자, 소멸자)

### ISSUE THREAD

**Issue by lopers-high** [42-CPP-GIT/CPP_GIT#12]
# ex00
## string: c++에서 제공하는 문자열 처리 클래스
char pointer와 다르게 마지막에 '\0'이 없다.
char pointer로 변환을 하려면 따로 작업을 해주어야 한다. (str.c_str())

## endl
버퍼의 끝에 개행을 추가해주고 버퍼를 비운다.
속도가 "\n"에 비해 느리기 때문에 특별한 이유가 없으면 "\n"을 쓰는게 좋아보인다.
```
std::cout << "hello" << std::endl;
std::cout << "hello" << "\n";
```

# ex01
## EOF: End Of File, 파일의 끝을 표현한 상수(-1)
파일을 읽을 때 파일의 끝에 도달하면 EOF를 반환해 파일의 끝을 알린다.
##CTRL+D
표준입력에서는 EOF 신호를 CTRL+D로 터미널에 보낼 수 있다.
ADD나 SEARCH 커맨드 입력 후 입력을 기다리고 있을 때 CTRL+D를 눌러 EOF가 감지되면 다시 초기화면으로 돌아가게 구현을 하고 싶었다.
```
while (1)
	{
		std::string	str;
		
		std::getline(std::cin, str);
		if (str == "ADD")
		{
			getline(std::cin, str);
			if (std::cin.eof())
				continue ;
		}
		...
		}
	}
```
프로그램 실행 결과 무한 루프가 돌았고
std::cin.clear()로 에러 플래그를 초기화하고
std::cin.ignore()로 버퍼를 비워도 상황은 같았다.
```
if (std::cin.eof())
{
	std::cin.clear();
	std::cin.clear();
	std::cout << std::cin.peek() << "\n";
	continue ;
}
```
출력 값:
`sh$ -1` 

터미널에서 표준입력을 받고 있는 상태에서 EOF를 보내게 되면 표준입력이 닫히게 되고 복구할 수 없게 된다.
이에 대한 해결방법으로는
- 프로세스를 fork해 자식 프로세스에서 입력을 처리
- 터미널 설정을 바꾸어 CTRL+D 입력을 처리 `tcgetattr(), tcsetattr()`
쉘을 구현하는 과제가 아니기에 CTRL+D를 입력받을 때 프로그램이 종료되도록 했습니다.

# ex02
## 생성자
클래스가 생성됨과 동시에 실행되는 멤버 함수
오버로딩이 가능하다.
private 생성자 : 기본 생성자 호출을 방지하기 위함
디자인 패턴중 싱글톤 패턴(객체를 하나만 생성 하도록 해, 생성된 객체를 어디에서든지 참조할 수 있도록 하는 패턴)을 위해 사용된다.
```
c++  -Wall -Wextra -Werror -std=c++98 -pedantic-errors  -c -o test.o test.cpp
test.cpp:27:10: error: calling a private constructor of class 'Account'
        Account tmp;
./Account.hpp:53:2: note: declared private here
        Account( void );
```
## 소멸자
객체가 소멸될 때 호출되는 멤버 함수(지역 변수의 스코프를 벗어났을 때, 동적 할당한 객체를 delete했을 때)
받는 인자가 없다.
반환 값이 없다.
명시적으로 호출이 불가능하다.
기본적으로 호출순서는 생성자의 역순
운영체제에 따라 호출되는 순서가 달라질 수 있다.

**Comment by change-challenge** [comment]
```
c++  -Wall -Wextra -Werror -std=c++98 -pedantic-errors  -c -o test.o test.cpp
test.cpp:27:10: error: calling a private constructor of class 'Account'
        Account tmp;
./Account.hpp:53:2: note: declared private here
        Account( void );
```

이건 무슨 뜻인가요?

**Comment by lopers-high** [comment]
@change-challenge 
private 멤버 함수로 기본생성자를 넣었을 때 생기는 컴파일 에러입니다.

**Comment by lopers-high** [comment]
이제 봤습니다. 자료 공유 감사합니다!
