### ISSUE TITLE
Q. private constructor는 왜 사용하는 건가요?

### ISSUE THREAD

**Issue by Giromi** [42-CPP-GIT/CPP_GIT#25]
# [stackoverflow - when-do-we-need-a-private-constructor-in-c](https://stackoverflow.com/questions/6568486/when-do-we-need-a-private-constructor-in-c)

1. Restricting object creation for all but friends; in this case all constructors have to be private
: 모든 friends에 대해서가 아니라 특정 객체들을 제한하기 위해서. 이러한 경우 모든 생성자는 private에 있어야 한다.
```c++
class A
{
    public:
        // other accessible methods
        friend class B;
    private:
	A () {}
};
```
```c++
class B
{
    public:
        A* Create_A () { return new A; }  // creation rights only with `B`
};
```

2. Restricting certain type of constructor (i.e. copy constructor, default constructor). e.g. std::fstream doesn't allow copying by such inaccessible constructor
: 생성자의 특정 타입을 제한하기위해서 (복사 생성자, 기본 생성자) 예를들어 std::fstream은 복사를 허락하지 않는다. 이러한 접근 불가능한 생성자에 의해서
```c++
class A
{
    public:
        A();
        A(int);
    private:
        A(const A&);  // C++03: Even `friend`s can't use this
        A(const A&) = delete;  // C++11: making `private` doesn't matter
};
```
3. To have a common delegate constructor, which is not supposed to be exposed to the outer world
: 공통 delegate한 생성자를 가지는 것 이것은 outer world로 노출되도록 supposed하지 않는다.

```c++
class A
{
    public:
        A (const B& b) : A(b.x_) {}
        A (const C& c) : A(c.foo()) {}
    private: 
        int x_;
        A (const int x) : x_(x) {} // common delegate; but within limits of `A`

};
```
4. For [singleton patterns](https://stackoverflow.com/q/86582/514235) when the singleton class is not inheritible (if it's inheritible then use a protected constructor)
: singleton pattern 때문에, singleton class는 inheritible하지 않는다. ( 만약 그것이 inheritible하면 protected constructor로 사용하여야 한다.

```c++
class Singleton
{
    public:
        static Singleton& getInstance() {
        Singleton object; // lazy initialization or use `new` & null-check
        return object;
   }
    private:
        Singleton() {}  // make `protected` for further inheritance
        Singleton(const Singleton&);  // inaccessible
        [Singleton& operator=(const Singleton&);  // inaccessible
};
```

**Comment by change-challenge** [comment]
https://htsstory.tistory.com/entry/C-private-%EC%83%9D%EC%84%B1%EC%9E%90
