### ISSUE TITLE
Q. public static 함수들을 사용하는 이유가 무엇인가요?

### ISSUE THREAD

**Issue by Giromi** [42-CPP-GIT/CPP_GIT#38]
# For static 변수
static 변수들을 다루기 위해 사용한다고 볼 수 있음.

```c++
class Zombie {
	public:
		Zombie(void);
		Zombie(std::string name);
		~Zombie(void);
		void	announce(void);
		static void	randomChump(std::string name);
		static Zombie	*newZombie(std::string name);
	private:
		std::string name_;
};
```
위와 같이 함수를 선언한다면 static관련된 함수들은 사실상 static변수들을 다루기 위한 함수가 아니기 때문에, static으로 함수로 굳이 선언할 필요가 없음. 그래서 Zombie클래스 밑에다가 선언하는 것이 오히려 더 맞는 표현임.

### My thinking
> 하나로 묶는다는 의미에서 static을 사용했다고 하지만, 이미 hpp파일에다가 선언했다는 점에서 하나로 묶였다고 생각할 수 있을듯

**Comment by change-challenge** [comment]
이거 저도 함수 아래에 따로 외부함수로 선언하는 것이 맞다고 생각하긴합니다.

**Comment by Giromi** [comment]
좋습니다! 오히려 함수의 의도를 헷갈릴 수 있지 않나 생각드네요.
