### ISSUE TITLE
[seungsle/cpp00/ex02] static 변수란?

### ISSUE THREAD

**Issue by aLVINlEE9** [42-CPP-GIT/CPP_GIT#4]
https://github.com/42-CPP-GIT/CPP_GIT/blob/ab9fc50bdb89bce9c72cc279c8ebbdd21ef85697/seungsle/CPP00/ex02/Account.cpp#L17

static 변수란?

- class 객체와 독립적으로 존재한다.
  - 객체로 접근 가능 + class 이름으로 접근가능
  `int Account::__nbAccounts = 0`

static 변수 선언 / 정의

- 선언
  - hpp파일에 static 변수가 선언되어있다.
  `static int _nbAccounts;`
  - 실제 메모리를 사용하지는 않음
- 정의
  `int Account::__nbAccounts = 0`
  - 실제 메모리가 할당된다

**반드시 전역 범위에서 정의 및 초기화를 해주어야 한다.**
- class 내부에서 초기화를 해주면 객체가 생성될때마다 계속해서 값이 덮어 씌워질 것이다.
- 모든 객체들이 static 변수를 공유하기 때문

https://ansohxxn.github.io/cpp/chapter8-10/

**Comment by jeongmino** [comment]
static 변수, 함수에 대한 정리를 잘 기록하신 덕에 이해가 잘 됬습니다 ㅎㅎ.
static 변수는 c언어의 전역변수와 비슷한 역할을 한다고 생각하면 될까요?

**Comment by aLVINlEE9** [comment]
https://ju3un.github.io/global-static/
위 블로그에 자세히 설명이 되어있네요!!
둘이 비슷한 성질은 가지지만 다른점도 있네요 참고하세요 ㅎㅎ
