### ISSUE TITLE
ifstream에서 eof와 good의 차이가 무엇인가요?

### ISSUE THREAD

**Issue by Giromi** [42-CPP-GIT/CPP_GIT#51]
### 일단 찾은 링크
https://stackoverflow.com/questions/4324441/testing-stream-good-or-stream-eof-reads-last-line-twice

**Comment by change-challenge** [comment]
eof는 우리가 아는 그 eof이고,
good을 알려면 그 c++의 bad bit, fail bit, good bit 이런 것들 찾아보면 좋을 것 같아요.

**Comment by Giromi** [comment]
아 감사합니다 bit관련되어서 찾아봐야하는군요!
